/** Worldwide airport catalog for trip-intake autocomplete. */

import type { Airport } from "@/types";

function a(code: string, city: string, name: string, country: string): Airport {
  return { code, city, name, country };
}

export const AIRPORTS: Airport[] = [
  // United States — hubs first
  a("ATL", "Atlanta", "Hartsfield-Jackson Atlanta International", "USA"),
  a("DFW", "Dallas", "Dallas/Fort Worth International", "USA"),
  a("DEN", "Denver", "Denver International", "USA"),
  a("ORD", "Chicago", "Chicago O'Hare International", "USA"),
  a("LAX", "Los Angeles", "Los Angeles International", "USA"),
  a("JFK", "New York", "John F. Kennedy International", "USA"),
  a("CLT", "Charlotte", "Charlotte Douglas International", "USA"),
  a("MCO", "Orlando", "Orlando International", "USA"),
  a("LAS", "Las Vegas", "Harry Reid International", "USA"),
  a("PHX", "Phoenix", "Phoenix Sky Harbor International", "USA"),
  a("MIA", "Miami", "Miami International", "USA"),
  a("SEA", "Seattle", "Seattle-Tacoma International", "USA"),
  a("IAH", "Houston", "George Bush Intercontinental", "USA"),
  a("EWR", "Newark", "Newark Liberty International", "USA"),
  a("SFO", "San Francisco", "San Francisco International", "USA"),
  a("MSP", "Minneapolis", "Minneapolis-Saint Paul International", "USA"),
  a("BOS", "Boston", "Boston Logan International", "USA"),
  a("DTW", "Detroit", "Detroit Metropolitan Wayne County", "USA"),
  a("PHL", "Philadelphia", "Philadelphia International", "USA"),
  a("LGA", "New York", "LaGuardia", "USA"),
  a("BWI", "Baltimore", "Baltimore/Washington International", "USA"),
  a("IAD", "Washington, D.C.", "Washington Dulles International", "USA"),
  a("DCA", "Washington, D.C.", "Ronald Reagan Washington National", "USA"),
  a("FLL", "Fort Lauderdale", "Fort Lauderdale-Hollywood International", "USA"),
  a("MDW", "Chicago", "Chicago Midway International", "USA"),
  a("TPA", "Tampa", "Tampa International", "USA"),
  a("SAN", "San Diego", "San Diego International", "USA"),
  a("PDX", "Portland", "Portland International", "USA"),
  a("HNL", "Honolulu", "Daniel K. Inouye International", "USA"),
  a("SLC", "Salt Lake City", "Salt Lake City International", "USA"),
  a("AUS", "Austin", "Austin-Bergstrom International", "USA"),
  a("BNA", "Nashville", "Nashville International", "USA"),
  a("RDU", "Raleigh", "Raleigh-Durham International", "USA"),
  a("MSY", "New Orleans", "Louis Armstrong New Orleans International", "USA"),
  a("STL", "St. Louis", "St. Louis Lambert International", "USA"),
  a("MCI", "Kansas City", "Kansas City International", "USA"),
  a("CLE", "Cleveland", "Cleveland Hopkins International", "USA"),
  a("PIT", "Pittsburgh", "Pittsburgh International", "USA"),
  a("IND", "Indianapolis", "Indianapolis International", "USA"),
  a("CMH", "Columbus", "John Glenn Columbus International", "USA"),
  a("CVG", "Cincinnati", "Cincinnati/Northern Kentucky International", "USA"),
  a("MKE", "Milwaukee", "Milwaukee Mitchell International", "USA"),
  a("BDL", "Hartford", "Bradley International", "USA"),
  a("RIC", "Richmond", "Richmond International", "USA"),
  a("ORF", "Norfolk", "Norfolk International", "USA"),
  a("JAX", "Jacksonville", "Jacksonville International", "USA"),
  a("CHS", "Charleston", "Charleston International", "USA"),
  a("SAV", "Savannah", "Savannah/Hilton Head International", "USA"),
  a("SAT", "San Antonio", "San Antonio International", "USA"),
  a("HOU", "Houston", "William P. Hobby", "USA"),
  a("DAL", "Dallas", "Dallas Love Field", "USA"),
  a("OKC", "Oklahoma City", "Will Rogers World", "USA"),
  a("TUL", "Tulsa", "Tulsa International", "USA"),
  a("OMA", "Omaha", "Eppley Airfield", "USA"),
  a("ABQ", "Albuquerque", "Albuquerque International Sunport", "USA"),
  a("ELP", "El Paso", "El Paso International", "USA"),
  a("TUS", "Tucson", "Tucson International", "USA"),
  a("SMF", "Sacramento", "Sacramento International", "USA"),
  a("OAK", "Oakland", "San Francisco Bay Oakland International", "USA"),
  a("SJC", "San Jose", "Norman Y. Mineta San Jose International", "USA"),
  a("SNA", "Orange County", "John Wayne Airport", "USA"),
  a("BUR", "Burbank", "Hollywood Burbank Airport", "USA"),
  a("ONT", "Ontario", "Ontario International", "USA"),
  a("PSP", "Palm Springs", "Palm Springs International", "USA"),
  a("RSW", "Fort Myers", "Southwest Florida International", "USA"),
  a("PBI", "West Palm Beach", "Palm Beach International", "USA"),
  a("MFE", "McAllen", "McAllen Miller International", "USA"),
  a("MEM", "Memphis", "Memphis International", "USA"),
  a("SDF", "Louisville", "Louisville Muhammad Ali International", "USA"),
  a("BHM", "Birmingham", "Birmingham-Shuttlesworth International", "USA"),
  a("TYS", "Knoxville", "McGhee Tyson", "USA"),
  a("GSO", "Greensboro", "Piedmont Triad International", "USA"),
  a("BUF", "Buffalo", "Buffalo Niagara International", "USA"),
  a("ROC", "Rochester", "Frederick Douglass Greater Rochester International", "USA"),
  a("SYR", "Syracuse", "Syracuse Hancock International", "USA"),
  a("ALB", "Albany", "Albany International", "USA"),
  a("PWM", "Portland", "Portland International Jetport", "USA"),
  a("BGR", "Bangor", "Bangor International", "USA"),
  a("ANC", "Anchorage", "Ted Stevens Anchorage International", "USA"),
  a("FAI", "Fairbanks", "Fairbanks International", "USA"),
  a("JNU", "Juneau", "Juneau International", "USA"),
  a("OGG", "Kahului", "Kahului Airport (Maui)", "USA"),
  a("KOA", "Kona", "Ellison Onizuka Kona International", "USA"),
  a("LIH", "Lihue", "Lihue Airport (Kauai)", "USA"),
  a("ITO", "Hilo", "Hilo International", "USA"),
  a("SJU", "San Juan", "Luis Muñoz Marín International", "USA"),
  a("STT", "St. Thomas", "Cyril E. King", "USA"),
  a("STX", "St. Croix", "Henry E. Rohlsen", "USA"),
  a("GUM", "Guam", "Antonio B. Won Pat International", "USA"),
  a("SPN", "Saipan", "Francisco C. Ada International", "USA"),
  a("BQN", "Aguadilla", "Rafael Hernández", "USA"),
  a("PSE", "Ponce", "Mercedita", "USA"),
  a("GRR", "Grand Rapids", "Gerald R. Ford International", "USA"),
  a("DAY", "Dayton", "Dayton International", "USA"),
  a("COS", "Colorado Springs", "Colorado Springs Airport", "USA"),
  a("BOI", "Boise", "Boise Airport", "USA"),
  a("GEG", "Spokane", "Spokane International", "USA"),
  a("RNO", "Reno", "Reno-Tahoe International", "USA"),
  a("FAT", "Fresno", "Fresno Yosemite International", "USA"),
  a("XNA", "Bentonville", "Northwest Arkansas National", "USA"),
  a("LIT", "Little Rock", "Bill and Hillary Clinton National", "USA"),
  a("JAN", "Jackson", "Jackson-Medgar Wiley Evers International", "USA"),
  a("MOB", "Mobile", "Mobile Regional", "USA"),
  a("PNS", "Pensacola", "Pensacola International", "USA"),
  a("VPS", "Destin", "Destin-Fort Walton Beach", "USA"),
  a("MYR", "Myrtle Beach", "Myrtle Beach International", "USA"),
  a("ILM", "Wilmington", "Wilmington International", "USA"),
  a("PVD", "Providence", "Rhode Island T.F. Green International", "USA"),
  a("MHT", "Manchester", "Manchester-Boston Regional", "USA"),
  a("BTV", "Burlington", "Burlington International", "USA"),

  // Canada
  a("YYZ", "Toronto", "Toronto Pearson International", "Canada"),
  a("YVR", "Vancouver", "Vancouver International", "Canada"),
  a("YUL", "Montreal", "Montréal-Trudeau International", "Canada"),
  a("YYC", "Calgary", "Calgary International", "Canada"),
  a("YEG", "Edmonton", "Edmonton International", "Canada"),
  a("YOW", "Ottawa", "Ottawa International", "Canada"),
  a("YHZ", "Halifax", "Halifax Stanfield International", "Canada"),
  a("YWG", "Winnipeg", "Winnipeg Richardson International", "Canada"),
  a("YQB", "Quebec City", "Québec City Jean Lesage International", "Canada"),

  // Mexico, Central America, Caribbean
  a("CUN", "Cancun", "Cancún International", "Mexico"),
  a("MEX", "Mexico City", "Mexico City International", "Mexico"),
  a("GDL", "Guadalajara", "Guadalajara International", "Mexico"),
  a("MTY", "Monterrey", "Monterrey International", "Mexico"),
  a("SJD", "Los Cabos", "Los Cabos International", "Mexico"),
  a("PVR", "Puerto Vallarta", "Licenciado Gustavo Díaz Ordaz International", "Mexico"),
  a("CZM", "Cozumel", "Cozumel International", "Mexico"),
  a("MID", "Merida", "Mérida International", "Mexico"),
  a("SJO", "San Jose", "Juan Santamaría International", "Costa Rica"),
  a("LIR", "Liberia", "Daniel Oduber Quirós International", "Costa Rica"),
  a("PTY", "Panama City", "Tocumen International", "Panama"),
  a("GUA", "Guatemala City", "La Aurora International", "Guatemala"),
  a("SAL", "San Salvador", "Óscar Arnulfo Romero International", "El Salvador"),
  a("MGA", "Managua", "Augusto C. Sandino International", "Nicaragua"),
  a("TGU", "Tegucigalpa", "Toncontín International", "Honduras"),
  a("HAV", "Havana", "José Martí International", "Cuba"),
  a("NAS", "Nassau", "Lynden Pindling International", "Bahamas"),
  a("MBJ", "Montego Bay", "Sangster International", "Jamaica"),
  a("KIN", "Kingston", "Norman Manley International", "Jamaica"),
  a("PUJ", "Punta Cana", "Punta Cana International", "Dominican Republic"),
  a("SDQ", "Santo Domingo", "Las Américas International", "Dominican Republic"),
  a("AUA", "Aruba", "Queen Beatrix International", "Aruba"),
  a("CUR", "Curacao", "Curaçao International", "Curaçao"),
  a("SXM", "St. Maarten", "Princess Juliana International", "Sint Maarten"),
  a("BGI", "Barbados", "Grantley Adams International", "Barbados"),
  a("POS", "Port of Spain", "Piarco International", "Trinidad and Tobago"),
  a("PLS", "Providenciales", "Providenciales International", "Turks and Caicos"),
  a("GCM", "Grand Cayman", "Owen Roberts International", "Cayman Islands"),
  a("BZE", "Belize City", "Philip S. W. Goldson International", "Belize"),

  // South America
  a("GRU", "Sao Paulo", "São Paulo/Guarulhos International", "Brazil"),
  a("GIG", "Rio de Janeiro", "Rio de Janeiro/Galeão International", "Brazil"),
  a("BSB", "Brasilia", "Brasília International", "Brazil"),
  a("EZE", "Buenos Aires", "Ministro Pistarini International", "Argentina"),
  a("AEP", "Buenos Aires", "Aeroparque Jorge Newbery", "Argentina"),
  a("SCL", "Santiago", "Arturo Merino Benítez International", "Chile"),
  a("LIM", "Lima", "Jorge Chávez International", "Peru"),
  a("BOG", "Bogota", "El Dorado International", "Colombia"),
  a("MDE", "Medellin", "José María Córdova International", "Colombia"),
  a("UIO", "Quito", "Mariscal Sucre International", "Ecuador"),
  a("GYE", "Guayaquil", "José Joaquín de Olmedo International", "Ecuador"),
  a("CCS", "Caracas", "Simón Bolívar International", "Venezuela"),
  a("MVD", "Montevideo", "Carrasco International", "Uruguay"),
  a("ASU", "Asuncion", "Silvio Pettirossi International", "Paraguay"),
  a("LPB", "La Paz", "El Alto International", "Bolivia"),

  // Europe
  a("LHR", "London", "London Heathrow", "United Kingdom"),
  a("LGW", "London", "London Gatwick", "United Kingdom"),
  a("STN", "London", "London Stansted", "United Kingdom"),
  a("LCY", "London", "London City", "United Kingdom"),
  a("MAN", "Manchester", "Manchester Airport", "United Kingdom"),
  a("EDI", "Edinburgh", "Edinburgh Airport", "United Kingdom"),
  a("GLA", "Glasgow", "Glasgow Airport", "United Kingdom"),
  a("BHX", "Birmingham", "Birmingham Airport", "United Kingdom"),
  a("DUB", "Dublin", "Dublin Airport", "Ireland"),
  a("SNN", "Shannon", "Shannon Airport", "Ireland"),
  a("CDG", "Paris", "Paris Charles de Gaulle", "France"),
  a("ORY", "Paris", "Paris Orly", "France"),
  a("NCE", "Nice", "Nice Côte d'Azur", "France"),
  a("LYS", "Lyon", "Lyon-Saint Exupéry", "France"),
  a("MRS", "Marseille", "Marseille Provence", "France"),
  a("AMS", "Amsterdam", "Amsterdam Schiphol", "Netherlands"),
  a("FRA", "Frankfurt", "Frankfurt Airport", "Germany"),
  a("MUC", "Munich", "Munich Airport", "Germany"),
  a("BER", "Berlin", "Berlin Brandenburg", "Germany"),
  a("DUS", "Dusseldorf", "Düsseldorf Airport", "Germany"),
  a("HAM", "Hamburg", "Hamburg Airport", "Germany"),
  a("MAD", "Madrid", "Adolfo Suárez Madrid-Barajas", "Spain"),
  a("BCN", "Barcelona", "Barcelona-El Prat", "Spain"),
  a("AGP", "Malaga", "Málaga-Costa del Sol", "Spain"),
  a("PMI", "Palma", "Palma de Mallorca", "Spain"),
  a("FCO", "Rome", "Rome Fiumicino", "Italy"),
  a("MXP", "Milan", "Milan Malpensa", "Italy"),
  a("LIN", "Milan", "Milan Linate", "Italy"),
  a("VCE", "Venice", "Venice Marco Polo", "Italy"),
  a("NAP", "Naples", "Naples International", "Italy"),
  a("ZRH", "Zurich", "Zurich Airport", "Switzerland"),
  a("GVA", "Geneva", "Geneva Airport", "Switzerland"),
  a("VIE", "Vienna", "Vienna International", "Austria"),
  a("BRU", "Brussels", "Brussels Airport", "Belgium"),
  a("CPH", "Copenhagen", "Copenhagen Airport", "Denmark"),
  a("ARN", "Stockholm", "Stockholm Arlanda", "Sweden"),
  a("OSL", "Oslo", "Oslo Gardermoen", "Norway"),
  a("HEL", "Helsinki", "Helsinki-Vantaa", "Finland"),
  a("LIS", "Lisbon", "Lisbon Humberto Delgado", "Portugal"),
  a("OPO", "Porto", "Francisco Sá Carneiro", "Portugal"),
  a("ATH", "Athens", "Athens International", "Greece"),
  a("SKG", "Thessaloniki", "Thessaloniki Airport", "Greece"),
  a("IST", "Istanbul", "Istanbul Airport", "Turkey"),
  a("SAW", "Istanbul", "Istanbul Sabiha Gökçen", "Turkey"),
  a("AYT", "Antalya", "Antalya Airport", "Turkey"),
  a("WAW", "Warsaw", "Warsaw Chopin", "Poland"),
  a("KRK", "Krakow", "Kraków John Paul II International", "Poland"),
  a("PRG", "Prague", "Václav Havel Airport Prague", "Czechia"),
  a("BUD", "Budapest", "Budapest Ferenc Liszt International", "Hungary"),
  a("OTP", "Bucharest", "Bucharest Henri Coandă", "Romania"),
  a("SOF", "Sofia", "Sofia Airport", "Bulgaria"),
  a("ZAG", "Zagreb", "Zagreb Franjo Tuđman", "Croatia"),
  a("DBV", "Dubrovnik", "Dubrovnik Airport", "Croatia"),
  a("SPU", "Split", "Split Airport", "Croatia"),
  a("BEG", "Belgrade", "Belgrade Nikola Tesla", "Serbia"),
  a("KEF", "Reykjavik", "Keflavík International", "Iceland"),
  a("LED", "St. Petersburg", "Pulkovo", "Russia"),
  a("SVO", "Moscow", "Sheremetyevo International", "Russia"),
  a("DME", "Moscow", "Domodedovo", "Russia"),
  a("KBP", "Kyiv", "Boryspil International", "Ukraine"),
  a("RIX", "Riga", "Riga International", "Latvia"),
  a("TLL", "Tallinn", "Tallinn Airport", "Estonia"),
  a("VNO", "Vilnius", "Vilnius Airport", "Lithuania"),
  a("MLA", "Malta", "Malta International", "Malta"),
  a("LCA", "Larnaca", "Larnaca International", "Cyprus"),

  // Middle East
  a("DXB", "Dubai", "Dubai International", "United Arab Emirates"),
  a("AUH", "Abu Dhabi", "Abu Dhabi International", "United Arab Emirates"),
  a("DOH", "Doha", "Hamad International", "Qatar"),
  a("RUH", "Riyadh", "King Khalid International", "Saudi Arabia"),
  a("JED", "Jeddah", "King Abdulaziz International", "Saudi Arabia"),
  a("TLV", "Tel Aviv", "Ben Gurion", "Israel"),
  a("AMM", "Amman", "Queen Alia International", "Jordan"),
  a("BEY", "Beirut", "Beirut-Rafic Hariri International", "Lebanon"),
  a("BAH", "Bahrain", "Bahrain International", "Bahrain"),
  a("MCT", "Muscat", "Muscat International", "Oman"),
  a("KWI", "Kuwait City", "Kuwait International", "Kuwait"),
  a("CAI", "Cairo", "Cairo International", "Egypt"),

  // Africa
  a("JNB", "Johannesburg", "O. R. Tambo International", "South Africa"),
  a("CPT", "Cape Town", "Cape Town International", "South Africa"),
  a("NBO", "Nairobi", "Jomo Kenyatta International", "Kenya"),
  a("ADD", "Addis Ababa", "Addis Ababa Bole International", "Ethiopia"),
  a("CMN", "Casablanca", "Mohammed V International", "Morocco"),
  a("RAK", "Marrakech", "Marrakech Menara", "Morocco"),
  a("LOS", "Lagos", "Murtala Muhammed International", "Nigeria"),
  a("ACC", "Accra", "Kotoka International", "Ghana"),
  a("DAR", "Dar es Salaam", "Julius Nyerere International", "Tanzania"),
  a("SEZ", "Mahe", "Seychelles International", "Seychelles"),
  a("MRU", "Mauritius", "Sir Seewoosagur Ramgoolam International", "Mauritius"),
  a("TUN", "Tunis", "Tunis-Carthage International", "Tunisia"),
  a("ALG", "Algiers", "Houari Boumediene", "Algeria"),

  // Asia
  a("NRT", "Tokyo", "Narita International", "Japan"),
  a("HND", "Tokyo", "Tokyo Haneda", "Japan"),
  a("KIX", "Osaka", "Kansai International", "Japan"),
  a("ITM", "Osaka", "Osaka Itami", "Japan"),
  a("NGO", "Nagoya", "Chubu Centrair International", "Japan"),
  a("FUK", "Fukuoka", "Fukuoka Airport", "Japan"),
  a("CTS", "Sapporo", "New Chitose", "Japan"),
  a("ICN", "Seoul", "Seoul Incheon International", "South Korea"),
  a("GMP", "Seoul", "Gimpo International", "South Korea"),
  a("PEK", "Beijing", "Beijing Capital International", "China"),
  a("PKX", "Beijing", "Beijing Daxing International", "China"),
  a("PVG", "Shanghai", "Shanghai Pudong International", "China"),
  a("SHA", "Shanghai", "Shanghai Hongqiao International", "China"),
  a("CAN", "Guangzhou", "Guangzhou Baiyun International", "China"),
  a("SZX", "Shenzhen", "Shenzhen Bao'an International", "China"),
  a("HKG", "Hong Kong", "Hong Kong International", "Hong Kong"),
  a("TPE", "Taipei", "Taiwan Taoyuan International", "Taiwan"),
  a("TSA", "Taipei", "Taipei Songshan", "Taiwan"),
  a("SIN", "Singapore", "Singapore Changi", "Singapore"),
  a("BKK", "Bangkok", "Suvarnabhumi", "Thailand"),
  a("DMK", "Bangkok", "Don Mueang International", "Thailand"),
  a("HKT", "Phuket", "Phuket International", "Thailand"),
  a("CNX", "Chiang Mai", "Chiang Mai International", "Thailand"),
  a("KUL", "Kuala Lumpur", "Kuala Lumpur International", "Malaysia"),
  a("PEN", "Penang", "Penang International", "Malaysia"),
  a("CGK", "Jakarta", "Soekarno-Hatta International", "Indonesia"),
  a("DPS", "Bali", "Ngurah Rai International", "Indonesia"),
  a("MNL", "Manila", "Ninoy Aquino International", "Philippines"),
  a("CEB", "Cebu", "Mactan-Cebu International", "Philippines"),
  a("SGN", "Ho Chi Minh City", "Tan Son Nhat International", "Vietnam"),
  a("HAN", "Hanoi", "Noi Bai International", "Vietnam"),
  a("DAD", "Da Nang", "Da Nang International", "Vietnam"),
  a("DEL", "Delhi", "Indira Gandhi International", "India"),
  a("BOM", "Mumbai", "Chhatrapati Shivaji Maharaj International", "India"),
  a("BLR", "Bangalore", "Kempegowda International", "India"),
  a("HYD", "Hyderabad", "Rajiv Gandhi International", "India"),
  a("MAA", "Chennai", "Chennai International", "India"),
  a("CCU", "Kolkata", "Netaji Subhas Chandra Bose International", "India"),
  a("GOI", "Goa", "Goa International", "India"),
  a("CMB", "Colombo", "Bandaranaike International", "Sri Lanka"),
  a("KTM", "Kathmandu", "Tribhuvan International", "Nepal"),
  a("DAC", "Dhaka", "Hazrat Shahjalal International", "Bangladesh"),
  a("ISB", "Islamabad", "Islamabad International", "Pakistan"),
  a("KHI", "Karachi", "Jinnah International", "Pakistan"),
  a("ALA", "Almaty", "Almaty International", "Kazakhstan"),
  a("TAS", "Tashkent", "Islam Karimov Tashkent International", "Uzbekistan"),
  a("EVN", "Yerevan", "Zvartnots International", "Armenia"),
  a("TBS", "Tbilisi", "Tbilisi International", "Georgia"),

  // Oceania
  a("SYD", "Sydney", "Sydney Kingsford Smith", "Australia"),
  a("MEL", "Melbourne", "Melbourne Airport", "Australia"),
  a("BNE", "Brisbane", "Brisbane Airport", "Australia"),
  a("PER", "Perth", "Perth Airport", "Australia"),
  a("ADL", "Adelaide", "Adelaide Airport", "Australia"),
  a("OOL", "Gold Coast", "Gold Coast Airport", "Australia"),
  a("CNS", "Cairns", "Cairns Airport", "Australia"),
  a("AKL", "Auckland", "Auckland Airport", "New Zealand"),
  a("WLG", "Wellington", "Wellington Airport", "New Zealand"),
  a("CHC", "Christchurch", "Christchurch Airport", "New Zealand"),
  a("NAN", "Nadi", "Nadi International", "Fiji"),
  a("PPT", "Papeete", "Faa'a International", "French Polynesia"),
  a("NOU", "Noumea", "La Tontouta International", "New Caledonia"),
  a("CBR", "Canberra", "Canberra Airport", "Australia"),
  a("HBA", "Hobart", "Hobart International", "Australia"),
  a("DRW", "Darwin", "Darwin International", "Australia"),
  a("ZQN", "Queenstown", "Queenstown Airport", "New Zealand"),
  a("RAR", "Rarotonga", "Rarotonga International", "Cook Islands"),
  a("APW", "Apia", "Faleolo International", "Samoa"),

  // Extra city airports — second/third hubs for major metros
  a("LTN", "London", "London Luton", "United Kingdom"),
  a("LBA", "Leeds", "Leeds Bradford", "United Kingdom"),
  a("NCL", "Newcastle", "Newcastle International", "United Kingdom"),
  a("BRS", "Bristol", "Bristol Airport", "United Kingdom"),
  a("ORK", "Cork", "Cork Airport", "Ireland"),
  a("BVA", "Paris", "Paris Beauvais", "France"),
  a("TLS", "Toulouse", "Toulouse-Blagnac", "France"),
  a("BOD", "Bordeaux", "Bordeaux-Mérignac", "France"),
  a("NTE", "Nantes", "Nantes Atlantique", "France"),
  a("CIA", "Rome", "Rome Ciampino", "Italy"),
  a("BGY", "Milan", "Milan Bergamo", "Italy"),
  a("BLQ", "Bologna", "Bologna Guglielmo Marconi", "Italy"),
  a("PSA", "Pisa", "Pisa International", "Italy"),
  a("FLR", "Florence", "Florence Airport", "Italy"),
  a("CTA", "Catania", "Catania-Fontanarossa", "Italy"),
  a("PMO", "Palermo", "Palermo Falcone-Borsellino", "Italy"),
  a("VLC", "Valencia", "Valencia Airport", "Spain"),
  a("ALC", "Alicante", "Alicante-Elche", "Spain"),
  a("SVQ", "Seville", "Seville Airport", "Spain"),
  a("BIO", "Bilbao", "Bilbao Airport", "Spain"),
  a("IBZ", "Ibiza", "Ibiza Airport", "Spain"),
  a("TFS", "Tenerife", "Tenerife South", "Spain"),
  a("LPA", "Gran Canaria", "Gran Canaria Airport", "Spain"),
  a("STR", "Stuttgart", "Stuttgart Airport", "Germany"),
  a("CGN", "Cologne", "Cologne Bonn Airport", "Germany"),
  a("EIN", "Eindhoven", "Eindhoven Airport", "Netherlands"),
  a("FAO", "Faro", "Faro Airport", "Portugal"),
  a("FNC", "Funchal", "Madeira Cristiano Ronaldo", "Portugal"),
  a("HER", "Heraklion", "Heraklion International", "Greece"),
  a("RHO", "Rhodes", "Rhodes International", "Greece"),
  a("CFU", "Corfu", "Corfu International", "Greece"),
  a("GOT", "Gothenburg", "Gothenburg Landvetter", "Sweden"),
  a("BGO", "Bergen", "Bergen Airport", "Norway"),
  a("GDN", "Gdansk", "Gdańsk Lech Wałęsa", "Poland"),
  a("LJU", "Ljubljana", "Ljubljana Jože Pučnik", "Slovenia"),
  a("TIA", "Tirana", "Tirana International", "Albania"),
  a("SKP", "Skopje", "Skopje International", "North Macedonia"),
  a("VKO", "Moscow", "Vnukovo International", "Russia"),
  a("YTZ", "Toronto", "Billy Bishop Toronto City", "Canada"),
  a("YYT", "St. John's", "St. John's International", "Canada"),
  a("YYJ", "Victoria", "Victoria International", "Canada"),
  a("YLW", "Kelowna", "Kelowna International", "Canada"),
  a("TIJ", "Tijuana", "Tijuana International", "Mexico"),
  a("MZT", "Mazatlan", "Mazatlán International", "Mexico"),
  a("HUX", "Huatulco", "Bahías de Huatulco International", "Mexico"),
  a("CTG", "Cartagena", "Rafael Núñez International", "Colombia"),
  a("CLO", "Cali", "Alfonso Bonilla Aragón International", "Colombia"),
  a("CUZ", "Cusco", "Alejandro Velasco Astete International", "Peru"),
  a("CGH", "Sao Paulo", "Congonhas", "Brazil"),
  a("SDU", "Rio de Janeiro", "Santos Dumont", "Brazil"),
  a("VCP", "Campinas", "Viracopos International", "Brazil"),
  a("COR", "Cordoba", "Ingeniero Aeronáutico Ambrosio L.V. Taravella", "Argentina"),
  a("MDZ", "Mendoza", "Governor Francisco Gabrielli International", "Argentina"),
  a("LGB", "Long Beach", "Long Beach Airport", "USA"),
  a("BZN", "Bozeman", "Bozeman Yellowstone International", "USA"),
  a("JAC", "Jackson Hole", "Jackson Hole Airport", "USA"),
  a("ASE", "Aspen", "Aspen/Pitkin County", "USA"),
  a("SBA", "Santa Barbara", "Santa Barbara Municipal", "USA"),
  a("MRY", "Monterey", "Monterey Regional", "USA"),
  a("DSM", "Des Moines", "Des Moines International", "USA"),
  a("MSN", "Madison", "Dane County Regional", "USA"),
  a("AVL", "Asheville", "Asheville Regional", "USA"),
  a("DWC", "Dubai", "Al Maktoum International", "United Arab Emirates"),
  a("SHJ", "Sharjah", "Sharjah International", "United Arab Emirates"),
  a("MED", "Medina", "Prince Mohammad bin Abdulaziz", "Saudi Arabia"),
  a("DMM", "Dammam", "King Fahd International", "Saudi Arabia"),
  a("MLE", "Male", "Velana International", "Maldives"),
  a("OKA", "Okinawa", "Naha Airport", "Japan"),
  a("PUS", "Busan", "Gimhae International", "South Korea"),
  a("CJU", "Jeju", "Jeju International", "South Korea"),
  a("KHH", "Kaohsiung", "Kaohsiung International", "Taiwan"),
  a("SUB", "Surabaya", "Juanda International", "Indonesia"),
  a("JOG", "Yogyakarta", "Yogyakarta International", "Indonesia"),
  a("BKI", "Kota Kinabalu", "Kota Kinabalu International", "Malaysia"),
  a("PNH", "Phnom Penh", "Phnom Penh International", "Cambodia"),
  a("RGN", "Yangon", "Yangon International", "Myanmar"),
  a("AMD", "Ahmedabad", "Sardar Vallabhbhai Patel International", "India"),
  a("COK", "Kochi", "Cochin International", "India"),
  a("PNQ", "Pune", "Pune International", "India"),
  a("JAI", "Jaipur", "Jaipur International", "India"),
  a("CTU", "Chengdu", "Chengdu Tianfu International", "China"),
  a("CKG", "Chongqing", "Chongqing Jiangbei International", "China"),
  a("HGH", "Hangzhou", "Hangzhou Xiaoshan International", "China"),
  a("XIY", "Xi'an", "Xi'an Xianyang International", "China"),
  a("DSS", "Dakar", "Blaise Diagne International", "Senegal"),
  a("ABJ", "Abidjan", "Félix-Houphouët-Boigny International", "Ivory Coast"),
  a("EBB", "Entebbe", "Entebbe International", "Uganda"),
  a("KGL", "Kigali", "Kigali International", "Rwanda"),
  a("DUR", "Durban", "King Shaka International", "South Africa"),
  a("WDH", "Windhoek", "Hosea Kutako International", "Namibia"),
  a("HRG", "Hurghada", "Hurghada International", "Egypt"),
  a("SSH", "Sharm El Sheikh", "Sharm El Sheikh International", "Egypt"),
  a("AGA", "Agadir", "Agadir Al Massira", "Morocco"),
  a("ANU", "Antigua", "V. C. Bird International", "Antigua and Barbuda"),
  a("UVF", "St. Lucia", "Hewanorra International", "Saint Lucia"),
  a("POP", "Puerto Plata", "Gregorio Luperón International", "Dominican Republic"),
];

export function airportLabel(airport: Airport) {
  return `${airport.city} (${airport.code}) — ${airport.name}`;
}

export function findAirport(code: string) {
  return AIRPORTS.find((airport) => airport.code === code.toUpperCase());
}

export function isUsAirport(code: string) {
  return findAirport(code)?.country === "USA";
}

export function searchAirports(query: string, limit = 24) {
  const q = query.trim().toLowerCase();
  if (!q) return AIRPORTS.slice(0, limit);
  const scored = AIRPORTS.map((airport) => {
    const code = airport.code.toLowerCase();
    const city = airport.city.toLowerCase();
    const name = airport.name.toLowerCase();
    const country = airport.country.toLowerCase();
    let score = 0;
    if (code === q) score = 100;
    else if (code.startsWith(q)) score = 80;
    else if (city === q) score = 70;
    else if (city.startsWith(q)) score = 60;
    else if (city.includes(q)) score = 40;
    else if (name.includes(q)) score = 30;
    else if (country.includes(q)) score = 20;
    else if (code.includes(q)) score = 10;
    return { airport, score };
  })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score || a.airport.city.localeCompare(b.airport.city));
  return scored.slice(0, limit).map((row) => row.airport);
}
